// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Reading_Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_BOOT
void ui_BOOT_screen_init(void);
void ui_event_BOOT(lv_event_t * e);
lv_obj_t * ui_BOOT;
lv_obj_t * ui_BootScreenLogo;
lv_obj_t * ui_Image2;


// SCREEN: ui_MAIN
void ui_MAIN_screen_init(void);
lv_obj_t * ui_MAIN;
lv_obj_t * ui_RPMRoot;
lv_obj_t * ui_GuageBG;
lv_obj_t * ui_RPMFG;
lv_obj_t * ui_RPM;
lv_obj_t * ui_SpeedRoot;
lv_obj_t * ui_Speed;
lv_obj_t * ui_SpeedBG;
lv_obj_t * ui_GearRoot;
lv_obj_t * ui_Gear;
lv_obj_t * ui_GearNum;
lv_obj_t * ui_TempRoot;
lv_obj_t * ui_Label5;
lv_obj_t * ui_SpeedIndicator;
lv_obj_t * ui_TempBG;
lv_obj_t * ui_TempIndicator;
lv_obj_t * ui_Logo;
lv_obj_t * ui_Image1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_group_[1] = {&ui_img_group_2_png};
const lv_img_dsc_t * ui_imgset_zfr_logo_800_[1] = {&ui_img_zfr_logo_800_480_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BOOT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_MAIN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1805, &ui_MAIN_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_BOOT_screen_init();
    ui_MAIN_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_BOOT);
}
