// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Reading_Display

#ifndef _READING_DISPLAY_UI_H
#define _READING_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_BOOT
void ui_BOOT_screen_init(void);
void ui_event_BOOT(lv_event_t * e);
extern lv_obj_t * ui_BOOT;
extern lv_obj_t * ui_BootScreenLogo;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_MAIN
void ui_MAIN_screen_init(void);
extern lv_obj_t * ui_MAIN;
extern lv_obj_t * ui_RPMRoot;
extern lv_obj_t * ui_GuageBG;
extern lv_obj_t * ui_RPMFG;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_SpeedRoot;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_SpeedBG;
extern lv_obj_t * ui_GearRoot;
extern lv_obj_t * ui_Gear;
extern lv_obj_t * ui_GearNum;
extern lv_obj_t * ui_TempRoot;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SpeedIndicator;
extern lv_obj_t * ui_TempBG;
extern lv_obj_t * ui_TempIndicator;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_zfr_logo_resized_png);    // assets/zfr_logo_resized.png
LV_IMG_DECLARE(ui_img_zfr_logo_800_480_png);    // assets/zfr_logo_800_480.png
LV_IMG_DECLARE(ui_img_1386757357);    // assets/BG (2).png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group 2.png
LV_IMG_DECLARE(ui_img_705273739);    // assets/output-onlinepngtools (2).png
LV_IMG_DECLARE(ui_img_guageindicatorresized_png);    // assets/GuageIndicatorResized.png
LV_IMG_DECLARE(ui_img_base_png);    // assets/Base.png



LV_FONT_DECLARE(ui_font_GearHigherFont);
LV_FONT_DECLARE(ui_font_rpmFont);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
