// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Reading_Display

#include "ui.h"

void ui_BOOT_screen_init(void)
{
    ui_BOOT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BOOT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BootScreenLogo = lv_img_create(ui_BOOT);
    lv_img_set_src(ui_BootScreenLogo, &ui_img_zfr_logo_resized_png);
    lv_obj_set_width(ui_BootScreenLogo, 120);
    lv_obj_set_height(ui_BootScreenLogo, 80);
    lv_obj_set_x(ui_BootScreenLogo, 462);
    lv_obj_set_y(ui_BootScreenLogo, 0);
    lv_obj_set_align(ui_BootScreenLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BootScreenLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BootScreenLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_BOOT);
    lv_img_set_src(ui_Image2, &ui_img_zfr_logo_800_480_png);
    lv_obj_set_width(ui_Image2, 800);
    lv_obj_set_height(ui_Image2, 480);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BOOT, ui_event_BOOT, LV_EVENT_ALL, NULL);

}
