// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Reading_Display

#include "ui.h"

void ui_MAIN_screen_init(void)
{
    ui_MAIN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MAIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPMRoot = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_RPMRoot, 800);
    lv_obj_set_height(ui_RPMRoot, 200);
    lv_obj_set_x(ui_RPMRoot, 5);
    lv_obj_set_y(ui_RPMRoot, 67);
    lv_obj_set_align(ui_RPMRoot, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_RPMRoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPMRoot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RPMRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPMRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GuageBG = lv_img_create(ui_RPMRoot);
    lv_img_set_src(ui_GuageBG, &ui_img_1386757357);
    lv_obj_set_width(ui_GuageBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GuageBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GuageBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GuageBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GuageBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPMFG = lv_slider_create(ui_GuageBG);
    lv_slider_set_value(ui_RPMFG, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_RPMFG) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_RPMFG, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMFG, 633);
    lv_obj_set_height(ui_RPMFG, 183);
    lv_obj_set_x(ui_RPMFG, 6);
    lv_obj_set_y(ui_RPMFG, -14);
    lv_obj_set_align(ui_RPMFG, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RPMFG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMFG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMFG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMFG, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMFG, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMFG, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RPMFG, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMFG, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMFG, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMFG, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RPM = lv_label_create(ui_GuageBG);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM, -212);
    lv_obj_set_y(ui_RPM, 5);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM, "10000 rpm");
    lv_obj_set_style_text_font(ui_RPM, &ui_font_rpmFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedRoot = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_SpeedRoot, 326);
    lv_obj_set_height(ui_SpeedRoot, 88);
    lv_obj_set_x(ui_SpeedRoot, -207);
    lv_obj_set_y(ui_SpeedRoot, 102);
    lv_obj_set_align(ui_SpeedRoot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedRoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SpeedRoot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed = lv_label_create(ui_SpeedRoot);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "Speed 200kmph");
    lv_obj_set_style_text_font(ui_Speed, &ui_font_rpmFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBG = lv_img_create(ui_MAIN);
    lv_img_set_src(ui_SpeedBG, &ui_img_705273739);
    lv_obj_set_width(ui_SpeedBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedBG, 185);
    lv_obj_set_y(ui_SpeedBG, 104);
    lv_obj_set_align(ui_SpeedBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeedBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GearRoot = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_GearRoot, 287);
    lv_obj_set_height(ui_GearRoot, 141);
    lv_obj_set_x(ui_GearRoot, 193);
    lv_obj_set_y(ui_GearRoot, 17);
    lv_obj_set_align(ui_GearRoot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearRoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GearRoot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GearRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GearRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gear = lv_label_create(ui_GearRoot);
    lv_obj_set_width(ui_Gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gear, -71);
    lv_obj_set_y(ui_Gear, -10);
    lv_obj_set_align(ui_Gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gear, "Gear");
    lv_obj_set_style_text_font(ui_Gear, &ui_font_rpmFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearNum = lv_label_create(ui_GearRoot);
    lv_obj_set_width(ui_GearNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GearNum, 31);
    lv_obj_set_y(ui_GearNum, -10);
    lv_obj_set_align(ui_GearNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GearNum, "5");
    lv_obj_set_style_text_font(ui_GearNum, &ui_font_GearHigherFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempRoot = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_TempRoot, 349);
    lv_obj_set_height(ui_TempRoot, 49);
    lv_obj_set_x(ui_TempRoot, -210);
    lv_obj_set_y(ui_TempRoot, 163);
    lv_obj_set_align(ui_TempRoot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempRoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempRoot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempRoot, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempRoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TempRoot);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Temperature 75C");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_rpmFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedIndicator = lv_slider_create(ui_MAIN);
    lv_slider_set_value(ui_SpeedIndicator, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SpeedIndicator) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SpeedIndicator, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedIndicator, 424);
    lv_obj_set_height(ui_SpeedIndicator, 10);
    lv_obj_set_x(ui_SpeedIndicator, 183);
    lv_obj_set_y(ui_SpeedIndicator, 104);
    lv_obj_set_align(ui_SpeedIndicator, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SpeedIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeedIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SpeedIndicator, &ui_img_guageindicatorresized_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeedIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedIndicator, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempBG = lv_img_create(ui_MAIN);
    lv_img_set_src(ui_TempBG, &ui_img_705273739);
    lv_obj_set_width(ui_TempBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempBG, 183);
    lv_obj_set_y(ui_TempBG, 164);
    lv_obj_set_align(ui_TempBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempIndicator = lv_slider_create(ui_MAIN);
    lv_slider_set_value(ui_TempIndicator, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TempIndicator) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TempIndicator, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_TempIndicator, 424);
    lv_obj_set_height(ui_TempIndicator, 10);
    lv_obj_set_x(ui_TempIndicator, 182);
    lv_obj_set_y(ui_TempIndicator, 164);
    lv_obj_set_align(ui_TempIndicator, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_TempIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_TempIndicator, &ui_img_guageindicatorresized_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempIndicator, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Logo = lv_img_create(ui_MAIN);
    lv_img_set_src(ui_Logo, &ui_img_zfr_logo_resized_png);
    lv_obj_set_width(ui_Logo, 120);
    lv_obj_set_height(ui_Logo, 80);
    lv_obj_set_x(ui_Logo, -322);
    lv_obj_set_y(ui_Logo, -167);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_MAIN);
    lv_img_set_src(ui_Image1, &ui_img_base_png);
    lv_obj_set_width(ui_Image1, 719);
    lv_obj_set_height(ui_Image1, 28);
    lv_obj_set_x(ui_Image1, 9);
    lv_obj_set_y(ui_Image1, 221);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
